language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
script: "npm run eslint && npm run test:cover"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
